MVCKutuphane/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCKutuphane.Models.Entity;
namespace MVCKutuphane.Controllers
{
    public class KategoriController : Controller
    {
        // GET: Kategori
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        [Authorize]
        public ActionResult Index()
        {
            var degerler = db.TBLKATEGORI.Where(x => x.DURUM == true).ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult KategoriEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult KategoriEkle(TBLKATEGORI p)
        {
            db.TBLKATEGORI.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KategoriSil(TBLKATEGORI k)
        {
            var ktgsil = db.TBLKATEGORI.Find(k.ID);
            ktgsil.DURUM = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KategoriGetir(int id)
        {
            var ktg = db.TBLKATEGORI.Find(id);
            return View("KategoriGetir", ktg);
        }
        public ActionResult KategoriGuncelle(TBLKATEGORI p)
        {
            var ktg = db.TBLKATEGORI.Find(p.ID);
            ktg.AD = p.AD;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
    }
}

MVCKutuphane/Views/Kategori/Index.cshtml
@using MVCKutuphane.Models.Entity
@model List<TBLKATEGORI>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h3>KATEGORİLER</h3>

<table class="table table-striped">
    <tr style="background-color:rgb(252, 178, 22)">
        <th>KATEGORİ ID</th>
        <th>KATEGORİ AD</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
    </tr>
    @foreach (var ktg in Model)
    {
        <tr>
            <th>@ktg.ID</th>
            <td>@ktg.AD</td>
            <td><a href="/Kategori/KategoriSil/@ktg.ID" class="btn btn-danger">SİL</a></td>
            <td><a href="/Kategori/KategoriGetir/@ktg.ID" class="btn btn-warning">GÜNCELLE</a></td>
        </tr>
    }
</table>
<a href="/Kategori/KategoriEkle/" class="btn btn-primary">Yeni Kategori Ekle</a>

MVCKutuphane/Views/Kategori/KategoriEkle.cshtml
@model MVCKutuphane.Models.Entity.TBLKATEGORI
@{
    ViewBag.Title = "KategoriEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">
    <div>
        <label>Kategori Adı</label>

        <br />
        <input type="text" class="form-control" name="AD" />
    </div>
    <br />
    <div>
        <button class="btn btn-info" id="Btn1">KATEGORİ EKLE</button>
    </div>
</form>

MVCKutuphane/Views/Kategori/KategoriGetir.cshtml
@model MVCKutuphane.Models.Entity.TBLKATEGORI
@{
    ViewBag.Title = "KategoriGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("KategoriGuncelle", "Kategori", FormMethod.Post))
{
    <div style="margin-bottom:25px"></div>
    <div class="form-group">
        @Html.LabelFor(k => k.ID)
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control", @readonly = true })
        <br />
        @Html.LabelFor(k => k.AD)
        @Html.TextBoxFor(k => k.AD, new { @class = "form-control" })
    </div>
    <div>
        <button class="btn btn-success">Güncelle</button>
    </div>
}