MVCKutuphane/Controllers/YazarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCKutuphane.Models.Entity;

namespace MVCKutuphane.Controllers
{
    public class YazarController : Controller
    {
        // GET: Yazar
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        public ActionResult Index()
        {

            var degerler = db.TBLYAZAR.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YazarEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YazarEkle(TBLYAZAR p)
        {
            if (!ModelState.IsValid)
            {
                return View("YazarEkle");
            }
            db.TBLYAZAR.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult YazarSil(int id)
        {
            var yazar = db.TBLYAZAR.Find(id);
            db.TBLYAZAR.Remove(yazar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult YazarGetir(int id)
        {
            var yzr = db.TBLYAZAR.Find(id);
            return View("YazarGetir", yzr);

        }
        public ActionResult YazarGuncelle(TBLYAZAR p)
        {
            var yzr = db.TBLYAZAR.Find(p.ID);
            yzr.AD = p.AD;
            yzr.SOYAD = p.SOYAD;
            yzr.DETAY = p.DETAY;
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        
        public ActionResult YazarKitaplar(int id)
        {
            var yazar = db.TBLKITAP.Where(x => x.YAZAR == id).ToList();
            var yazarad = db.TBLYAZAR.Where(x => x.ID == id).Select(z => z.AD + " " + z.SOYAD).FirstOrDefault();
            ViewBag.yazarad1 = yazarad;
            return View(yazar);
        }
    }
}

MVCKutuphane/Views/Yazar/Index.cshtml
@using MVCKutuphane.Models.Entity
@model List<TBLYAZAR>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h3>YAZARLAR</h3>
<table class="table table-striped">
    <tr style="background-color:rgb(252, 178, 22)">
        <th>YAZAR ID</th>
        <th>YAZAR AD</th>
        <th>YAZAR SOYAD</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        <th>YAZARIN KİTAPLARI</th>
    </tr>
    @foreach (var yzr in Model)
    {
        <tr>
            <th>@yzr.ID</th>
            <td>@yzr.AD</td>
            <td>@yzr.SOYAD</td>
            <td>@Html.ActionLink("Sil", "YazarSil", new { id = yzr.ID }, new { @class = "btn btn-danger", onclick = "return confirm('Silmek istiyor musunuz?')" })</td>
            <td><a href="/Yazar/YazarGetir/@yzr.ID" class="btn btn-warning">GÜNCELLE</a></td>
            <td><a href="/Yazar/YazarKitaplar/@yzr.ID" class="btn btn-success" >Yazarın Kitapları</a></td>
        </tr>
    }
</table>
<a href="/Yazar/YazarEkle/" class="btn btn-primary">Yeni Yazar Ekle</a>

MVCKutuphane/Views/Yazar/YazarEkle.cshtml
@model MVCKutuphane.Models.Entity.TBLYAZAR
@{
    ViewBag.Title = "YazarEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">
    <div></div>
    <div style="margin-top:15px">
        <label>Yazar Adı</label>
        @Html.TextBoxFor(y=>y.AD, new { @class = "form-control", @placeholder = "Ad Giriniz.." })
        @Html.ValidationMessageFor(y => y.AD)
    </div>
    <div style="margin-top:15px">
        <label>Yazar Soyadı</label>
        @Html.TextBoxFor(y=>y.SOYAD, new { @class="form-control", @placeholder="Soyad Giriniz.."})
        @Html.ValidationMessageFor(y=>y.SOYAD)
    </div>
    <div style="margin-top:15px">   
        <label>Yazar Detay</label>
        @Html.TextAreaFor(y=>y.DETAY, new { @class="form-control", @placeholder = "Detay Giriniz..", rows = "7", cols = "70" })
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info">Yazar Ekle</button>
    </div>
</form>

MVCKutuphane/Views/Yazar/YazarGetir.cshtml
@model MVCKutuphane.Models.Entity.TBLYAZAR
@{
    ViewBag.Title = "YazarGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("YazarGuncelle", "Yazar", FormMethod.Post))
{
    <div style="margin-bottom:25px"></div>
    <div class="form-group">
        @Html.LabelFor(y => y.ID)
        @Html.TextBoxFor(y => y.ID, new { @class = "form-control", @readonly = true })
        <br />
        @Html.LabelFor(y => y.AD)
        @Html.TextBoxFor(y => y.AD, new { @class = "form-control" })
        <br />
        @Html.LabelFor(y => y.SOYAD)
        @Html.TextBoxFor(y => y.SOYAD, new { @class = "form-control" })
        <br />
        @Html.LabelFor(y => y.DETAY)
        @Html.TextAreaFor(y => y.DETAY, new { @class = "form-control", rows = "7", cols = "70" })
    </div>
    <div>
        <button class="btn btn-success">Güncelle</button>
    </div>
}

MVCKutuphane/Views/Yazar/YazarKitaplar.cshtml
@using MVCKutuphane.Models.Entity;
@model List<TBLKITAP>
@{
    ViewBag.Title = "YazarKitaplar";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>@ViewBag.yazarad1</h2>

<br />

<table class="table table-striped">
    <tr style="background-color:rgb(252, 178, 22)">
        <th>ID</th>
        <th>Kitap Adı</th>
        <th>Kategori</th>
        <th>Yayınevi</th>
    </tr>
    @foreach (var i in Model)
    {
        <tr>
            <td>@i.ID</td>
            <td>@i.AD</td>
            <td>@i.TBLKATEGORI.AD</td>
            <td>@i.YAYINEVI</td>
        </tr>
    }
</table>